import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  CalendarIcon,
  ChevronDownIcon,
  HomeIcon,
  BarChartIcon,
  FileTextIcon,
  UsersIcon,
  CreditCardIcon,
  BookOpenIcon,
  HelpCircleIcon,
} from "lucide-react";
import { Button } from "@/components/ui/Button";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-gray-100">
          {/* Sidebar */}
          <aside className="w-64 bg-white shadow-md">
            <div className="p-4 border-b">
              <h1 className="text-xl font-bold">CO2 Visualization</h1>
            </div>
            <nav className="p-4">
              <ul className="space-y-2">
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <HomeIcon className="mr-2" size={18} /> ダッシュボード
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <BarChartIcon className="mr-2" size={18} /> CO2見える化
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <FileTextIcon className="mr-2" size={18} /> 集計ルール管理
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <UsersIcon className="mr-2" size={18} /> 会社情報
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <CreditCardIcon className="mr-2" size={18} /> CO2削減目標
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="flex items-center text-gray-600 hover:text-gray-800"
                  >
                    <BookOpenIcon className="mr-2" size={18} /> マニュアル
                  </a>
                </li>
              </ul>
            </nav>
          </aside>

          <main className="flex-1 p-8 overflow-auto">{children}</main>

          {/* Help button */}
          <div className="fixed bottom-4 right-4">
            <Button className="bg-teal-500 hover:bg-teal-600 text-white">
              <HelpCircleIcon className="mr-2" size={18} />
              Need help?
            </Button>
          </div>
        </div>
      </body>
    </html>
  );
}
