import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  CalendarIcon,
  ChevronDownIcon,
  HomeIcon,
  BarChartIcon,
  FileTextIcon,
  UsersIcon,
  CreditCardIcon,
  BookOpenIcon,
  HelpCircleIcon,
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import Sidebar from "@/components/ui/Sidebar";
import Header from "@/components/ui/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-gray-100 text-primary-text">
          {/* Sidebar */}
          <Sidebar />

          <div className="w-screen">
            <Header />
            <main className="flex-1 p-8 overflow-auto">{children}</main>
          </div>

          {/* Help button */}
          <div className="fixed bottom-4 right-4">
            <Button className="bg-teal-500 hover:bg-teal-600 text-white">
              <HelpCircleIcon className="mr-2" size={18} />
              Need help?
            </Button>
          </div>
        </div>
      </body>
    </html>
  );
}
